# -*- coding: utf-8 -*-
"""New2026tests01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bnVB4-UGovPfrAK40cg8iuDToVvqV6MS
"""

import random

# Генерируем список из 20 случайных чисел
random_list = [random.randint(1, 1000) for _ in range(20)]

print("Исходный список:", random_list)
print("\nДлина списка: ", len(random_list))

import time

# Декоратор для измерения времени выполнения функции
def timer(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"\nВремя выполнения функции '{func.__name__}': {end_time - start_time:.6f} секунд")
        return result
    return wrapper

# Реализация сортировки пузырьком (Bubble Sort) с декоратором
@timer
def bubble_sort(arr):
    n = len(arr)
    for i in range(n - 1):
        for j in range(n - 1 - i):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr

# Создаем копию random_list для тестирования функции сортировки
list_to_sort = list(random_list)

# Выполняем сортировку, время будет измерено декоратором
sorted_list_manual = bubble_sort(list_to_sort)

print(f"\nОтсортированный список (вручную): {sorted_list_manual}")

!pip list

import random

# Определяем типы животных, их виды и диапазоны длин
animal_types = {
    'кошка': {
        'species': ['Мейн-кун', 'Сиамская', 'Персидская', 'Британская', 'Сфинкс'],
        'tail_length_range': (20, 40), # cm
        'fur_length_range': (1, 15),  # cm
        'body_length_range': (30, 100) # cm
    },
    'собака': {
        'species': ['Лабрадор', 'Пудель', 'Чихуахуа', 'Немецкая овчарка', 'Бульдог'],
        'tail_length_range': (10, 50), # cm
        'fur_length_range': (1, 20),  # cm
        'body_length_range': (20, 120) # cm
    },
    'хомяк': {
        'species': ['Джунгарский', 'Сирийский', 'Роборовского'],
        'tail_length_range': (1, 3),   # cm
        'fur_length_range': (1, 2),    # cm (rounding up from potential 0.5)
        'body_length_range': (5, 20)   # cm
    }
}

data = []
num_animals = 50

for _ in range(num_animals):
    common_name = random.choice(list(animal_types.keys()))
    details = animal_types[common_name]

    species_name = random.choice(details['species'])
    tail_length = random.randint(*details['tail_length_range'])
    fur_length = random.randint(*details['fur_length_range'])
    body_length = random.randint(*details['body_length_range'])

    data.append([common_name, species_name, tail_length, fur_length, body_length])

print(f"Создана таблица 'data' с {len(data)} записями.")
print("Первые 5 записей:")
for i in range(min(5, len(data))):
    print(data[i])

print("\nПоследние 5 записей:")
for i in range(max(0, len(data) - 5), len(data)):
    print(data[i])

def cprint(data):
    for line in data:
        for info in line:
            print(info, end='\t')
        print()

cprint(data)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Преобразуем список списков в pandas DataFrame для удобства
df = pd.DataFrame(data, columns=['общее название', 'название вида', 'длина хвоста', 'длина шерсти', 'длина тела'])

# Определяем признаки (X) и целевую переменную (y)
# Признаки: длина хвоста, длина шерсти, длина тела
X = df[['длина хвоста', 'длина шерсти', 'длина тела']]
# Целевая переменная: общее название
y = df['общее название']

# Кодируем целевую переменную (общее название) в числовой формат
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Разделяем данные на обучающую и тестовую выборки
# test_size=0.2 означает, что 20% данных пойдут на тестирование, 80% на обучение
# random_state для воспроизводимости результатов
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

print("Данные успешно подготовлены для обучения:")
print(f"Размер обучающей выборки (признаки): {X_train.shape}")
print(f"Размер обучающей выборки (целевая переменная): {y_train.shape}")
print(f"Размер тестовой выборки (признаки): {X_test.shape}")
print(f"Размер тестовой выборки (целевая переменная): {y_test.shape}")
print("\nПример закодированных целевых переменных (0: кошка, 1: собака, 2: хомяк - порядок может варьироваться):", label_encoder.classes_)

# Обучение и оценка модели с оптимальным количеством соседей (best_n_neighbors = 2)
# Используем значение best_n_neighbors, которое мы нашли ранее
knn = KNeighborsClassifier(n_neighbors=best_n_neighbors)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"\nТочность модели KNeighborsClassifier с n_neighbors={best_n_neighbors} на тестовой выборке: {accuracy:.2f}")

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Определяем диапазон значений для n_neighbors
n_neighbors_range = range(1, 15) # От 1 до 14 соседей

accuracies = []

for n in n_neighbors_range:
    # Инициализируем модель KNeighborsClassifier с текущим n_neighbors
    knn = KNeighborsClassifier(n_neighbors=n)

    # Обучаем модель на обучающих данных
    knn.fit(X_train, y_train)

    # Делаем предсказания на тестовых данных
    y_pred = knn.predict(X_test)

    # Оцениваем точность модели
    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)

    print(f"n_neighbors: {n}, Точность: {accuracy:.2f}")

# Находим лучшее значение n_neighbors и соответствующую точность
best_n_neighbors = n_neighbors_range[accuracies.index(max(accuracies))]
best_accuracy = max(accuracies)

print(f"\nОптимальное количество соседей (n_neighbors): {best_n_neighbors}")
print(f"Лучшая точность: {best_accuracy:.2f}")

import seaborn as sns
import matplotlib.pyplot as plt

# Используем только числовые признаки и целевую переменную для pairplot
# hue='общее название' позволит увидеть разделение по типам животных
sns.pairplot(df, vars=['длина хвоста', 'длина шерсти', 'длина тела'], hue='общее название', palette='viridis')
plt.suptitle('Pairplot распределения признаков по типу животного', y=1.02) # Добавляем общий заголовок
plt.show()

average_body_length = df.groupby('общее название')['длина тела'].mean().reset_index()
print("Средняя длина тела для каждого типа животного:")
display(average_body_length)

from sklearn.neighbors import KNeighborsClassifier

types = ["Хомяк", "Кошка", "Собака"]
size = [0, 1, 2] # 0 - маленькое, 1 - среднее, 2 - большое
noize_level = [0, 1, 2] # 0 - тихое, 1 - не самое тихое, 2 - громкое

X = [[size[i], noize_level[i]] for i in range(len(types))]
y = types

model = KNeighborsClassifier(n_neighbors=1)
model.fit(X, y)

new_size = 0
new_noize_level = 1

prediction = model.predict([[new_size, new_noize_level]])
print(f"Предсказание типа животного: {prediction[0]}")

# Функция для визуализации дерева
def visualize_tree(model, feature_names, class_names):
    plt.figure(figsize=(10, 6))
    plot_tree(model, feature_names=feature_names, class_names=class_names, filled=True)
    plt.title("Решающее дерево")
    plt.show()

import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

df = pd.read_csv("inozoo.csv")

X = df[['длина', 'громкость']].values
y = df['животное'].values

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X, y)

data = {'длина' : [550, 185, 50, 95],'громкость': [120, 185, 65, 60]}

new_animals = pd.DataFrame(data).values
predictions = model.predict(new_animals)
print(predictions)

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Путь к файлу на вашем Google Диске
# file_path = '/content/drive/MyDrive/Colab Notebooks/inozoo.csv'
file_path = './inozoo.csv'

# Чтение датасета
df = pd.read_csv(file_path)
df.head()

import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

data = pd.read_csv("./dragons_dataset.csv")
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

knn_model = KNeighborsClassifier(n_neighbors=3)
knn_model.fit(X_train, y_train)

knn_predictions = knn_model.predict(X_val)
knn_accuracy = accuracy_score(y_val, knn_predictions)
print(knn_accuracy)