# -*- coding: utf-8 -*-
"""triangs-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ro6wdSFBJT_05snn1XyODn2GX-9BVnA
"""

import numpy as np
import itertools
import matplotlib.pyplot as plt

# 1. Создание 10 случайных точек на плоскости с координатами от -10 до +10
np.random.seed(42) # Для воспроизводимости результатов
points = np.random.uniform(-10, 10, size=(10, 2))

print("Случайные точки:")
for i, p in enumerate(points):
    print(f"  Точка {i+1}: ({p[0]:.2f}, {p[1]:.2f})")

# 2. Получение всех возможных комбинаций из 3 точек для формирования треугольников
triangles = list(itertools.combinations(points, 3))
print(f"\nВсего возможных треугольников: {len(triangles)}")

# Функция для расчета площади треугольника по координатам вершин
def triangle_area(p1, p2, p3):
    # Используем формулу определителя: 0.5 * |x1(y2 - y3) + x2(y3 - y1) + x3(y1 - y2)|
    return 0.5 * abs(p1[0]*(p2[1] - p3[1]) + p2[0]*(p3[1] - p1[1]) + p3[0]*(p1[1] - p2[1]))

# 3. Нахождение треугольника с минимальной площадью
min_area = float('inf')
min_area_triangle = None

for tri in triangles:
    area = triangle_area(tri[0], tri[1], tri[2])
    if area < min_area:
        min_area = area
        min_area_triangle = tri

print(f"\nМинимальная площадь треугольника: {min_area:.2f}")
if min_area_triangle:
    p1, p2, p3 = min_area_triangle
    print(f"Вершины треугольника с минимальной площадью:")
    print(f"  P1: ({p1[0]:.2f}, {p1[1]:.2f})")
    print(f"  P2: ({p2[0]:.2f}, {p2[1]:.2f})")
    print(f"  P3: ({p3[0]:.2f}, {p3[1]:.2f})")

# 4. Визуализация точек и закрашивание треугольника с минимальной площадью зеленым цветом
plt.figure(figsize=(8, 8))
plt.scatter(points[:, 0], points[:, 1], color='blue', zorder=5, label='Все точки')

plt.title("Случайные точки и треугольник с минимальной площадью")
plt.xlabel("X-координата")
plt.ylabel("Y-координата")
plt.grid(True)

# Построение всех возможных треугольников черным цветом (с низкой прозрачностью)
for i, tri in enumerate(triangles):
    p1, p2, p3 = tri
    # Рисуем стороны треугольника
    plt.plot([p1[0], p2[0]], [p1[1], p2[1]], 'k-', alpha=0.05, zorder=1) # Черные линии, низкая прозрачность
    plt.plot([p2[0], p3[0]], [p2[1], p3[1]], 'k-', alpha=0.05, zorder=1)
    plt.plot([p3[0], p1[0]], [p3[1], p1[1]], 'k-', alpha=0.05, zorder=1)

# Построение треугольника с минимальной площадью
if min_area_triangle:
    p1, p2, p3 = min_area_triangle
    triangle_polygon = plt.Polygon([p1, p2, p3], color='green', alpha=0.5, zorder=2, label='Минимальная площадь')
    plt.gca().add_patch(triangle_polygon)
    # Дополнительно рисуем линии для четкости
    plt.plot([p1[0], p2[0]], [p1[1], p2[1]], 'g-', linewidth=2, zorder=3)
    plt.plot([p2[0], p3[0]], [p2[1], p3[1]], 'g-', linewidth=2, zorder=3)
    plt.plot([p3[0], p1[0]], [p3[1], p1[1]], 'g-', linewidth=2, zorder=3)

plt.xlim(-12, 12)
plt.ylim(-12, 12)
plt.gca().set_aspect('equal', adjustable='box')
plt.legend()
plt.show()