# -*- coding: utf-8 -*-
"""Modelling-Astro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xgRwsrDd3AUaVzcTOYdK3rQqJFFv4Oi
"""

import sys
print(sys.version)

"""### Particle Simulation with Visualization

This program will simulate the movement of a large number of particles within a confined space. Each particle will have a random initial position, velocity, and direction. We will use `matplotlib` to visualize their movement over time.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

"""First, let's define a `Particle` class to encapsulate the properties and behavior of each particle."""

class Particle:
    def __init__(self, x_limit, y_limit):
        self.position = np.array([np.random.rand() * x_limit, np.random.rand() * y_limit])
        angle = np.random.rand() * 2 * np.pi
        self.velocity = np.array([np.cos(angle), np.sin(angle)]) * (np.random.rand() * 0.05 + 0.01) # Random speed
        self.radius = 0.005 # Small radius for visualization

    def update(self, dt, x_limit, y_limit):
        self.position += self.velocity * dt

        # Bounce off walls
        if not (0 <= self.position[0] <= x_limit):
            self.velocity[0] *= -1
            self.position[0] = np.clip(self.position[0], 0, x_limit) # Reposition to avoid getting stuck
        if not (0 <= self.position[1] <= y_limit):
            self.velocity[1] *= -1
            self.position[1] = np.clip(self.position[1], 0, y_limit) # Reposition to avoid getting stuck

"""Now, let's set up the simulation parameters and create a list of particles."""

NUM_PARTICLES = 500 # You can increase this for more particles
X_LIMIT = 1.0
Y_LIMIT = 1.0
DT = 0.01 # Time step

particles = [Particle(X_LIMIT, Y_LIMIT) for _ in range(NUM_PARTICLES)]

# Setup the plot for animation
fig, ax = plt.subplots(figsize=(8, 8))
ax.set_xlim(0, X_LIMIT)
ax.set_ylim(0, Y_LIMIT)
ax.set_aspect('equal', adjustable='box')
ax.set_title('Particle Simulation')

# Create a scatter plot for particles
scatter = ax.scatter([p.position[0] for p in particles],
                     [p.position[1] for p in particles],
                     s=1) # Marker size

def update_animation(frame):
    for p in particles:
        p.update(DT, X_LIMIT, Y_LIMIT)
    scatter.set_offsets([[p.position[0], p.position[1]] for p in particles])
    return scatter,

# Create the animation
# Note: This might take a moment to render depending on NUM_PARTICLES and interval.
animation = FuncAnimation(fig, update_animation, frames=range(200),
                          interval=50, blit=True)

plt.rcParams['animation.html'] = 'jshtml' # Required for animation to display in Colab
display(animation)

"""### Planetary Motion Simulation

This simulation will model the movement of several planets around a central star, considering not only the star's gravitational pull but also the mutual gravitational attractions between the planets themselves. This is an N-body problem, and we'll use simplified physics for visualization.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

# Define gravitational constant (can be scaled for simulation purposes)
G = 1.0

"""We'll define a `CelestialBody` class to represent the star and each planet. Each body will have a mass, position, velocity, and a way to update its state based on gravitational forces."""

class CelestialBody:
    def __init__(self, mass, position, velocity, color='blue', size=10):
        self.mass = mass
        self.position = np.array(position, dtype=float)
        self.velocity = np.array(velocity, dtype=float)
        self.color = color
        self.size = size

    def update_position(self, dt):
        self.position += self.velocity * dt

"""Now, let's set up the initial conditions for our star and planets. We'll give them initial positions and velocities that should result in somewhat stable orbits, but mutual interactions will add complexity."""

import matplotlib
# Simulation parameters
SIM_TIME_STEP = 0.01  # dt
ANIMATION_FRAMES = None # Set to None for continuous animation
PLOT_LIMIT = 60 # Extent of the plot area, increased slightly for more planets

# Create the star
star = CelestialBody(mass=1000, position=[0, 0], velocity=[0, 0], color='orange', size=100)

# Create planets (initial positions and velocities are key for stable orbits)
# Orbital velocity for a circular orbit: v = sqrt(G*M/r)

planets = []
NUM_PLANETS = 10
BASE_RADIUS = 15
ORBITAL_SPACING = 2.5 # Reduced spacing for closer orbits
PLANET_MASS_BASE = 5 # Increased mass for more noticeable interaction

for i in range(NUM_PLANETS):
    current_radius = BASE_RADIUS + i * ORBITAL_SPACING
    # Add a small random offset to initial position
    initial_angle = np.random.rand() * 2 * np.pi
    initial_position = np.array([current_radius * np.cos(initial_angle), current_radius * np.sin(initial_angle)])

    # Calculate ideal orbital velocity for circular orbit
    current_velocity_magnitude = np.sqrt(G * star.mass / current_radius)
    # Perpendicular direction to position vector
    initial_velocity = np.array([-np.sin(initial_angle), np.cos(initial_angle)]) * current_velocity_magnitude

    # Add a small random perturbation to velocity
    initial_velocity += (np.random.rand(2) - 0.5) * 0.5 # Small random perturbation

    planet_mass = PLANET_MASS_BASE + np.random.rand() * 2 # Slightly varied planet masses
    planet_color = matplotlib.colormaps['hsv'](i / NUM_PLANETS) # Different colors for each planet
    planet_size = 15 + np.random.rand() * 10 # Varied planet sizes

    planets.append(CelestialBody(mass=planet_mass, position=initial_position,
                                 velocity=initial_velocity, color=planet_color, size=planet_size))


all_bodies = [star] + planets

# Setup the plot for animation
fig, ax = plt.subplots(figsize=(10, 10))
ax.set_xlim(-PLOT_LIMIT, PLOT_LIMIT)
ax.set_ylim(-PLOT_LIMIT, PLOT_LIMIT)
ax.set_aspect('equal', adjustable='box')
ax.set_title('Planetary Motion Simulation (N-body)')
ax.set_facecolor('black') # Space-like background

# Create scatter plots for each body
body_plots = []
for body in all_bodies:
    plot, = ax.plot(body.position[0], body.position[1], 'o', color=body.color, markersize=np.sqrt(body.size))
    body_plots.append(plot)

def update_planetary_animation(frame):
    # Extract positions and masses into NumPy arrays
    positions = np.array([body.position for body in all_bodies]) # (N, 2)
    masses = np.array([body.mass for body in all_bodies]) # (N,)

    N = len(all_bodies)

    # Calculate all pairwise difference vectors (r_vecs[i, j] = body_j.position - body_i.position)
    r_vecs = positions[np.newaxis, :, :] - positions[:, np.newaxis, :] # Shape (N, N, 2)

    # Calculate pairwise distances
    distances = np.linalg.norm(r_vecs, axis=2) # Shape (N, N)

    # Create a mask to exclude self-interaction (i.e., when i == j)
    # Replace zeros with a tiny value to prevent division by zero for force direction calculation
    distances[distances == 0] = 1e-9 # Small epsilon to prevent division by zero

    # Calculate force magnitudes (G * m_i * m_j / r^2)
    force_magnitudes = G * masses[:, np.newaxis] * masses[np.newaxis, :] / (distances**2) # Shape (N, N)

    # Set self-interaction forces (magnitudes) to zero
    np.fill_diagonal(force_magnitudes, 0)

    # Calculate force directions (unit vectors)
    force_directions = r_vecs / distances[:, :, np.newaxis] # Shape (N, N, 2)

    # Calculate individual force vectors F_ij
    forces_ij = force_magnitudes[:, :, np.newaxis] * force_directions # Shape (N, N, 2)

    # Sum all forces acting on each body
    total_forces = np.sum(forces_ij, axis=1) # Shape (N, 2)

    # Update velocities and positions for all bodies
    for i, body in enumerate(all_bodies):
        # Update velocity (acceleration = force / mass)
        body.velocity += (total_forces[i] / body.mass) * SIM_TIME_STEP
        # Update position
        body.position += body.velocity * SIM_TIME_STEP

        # Update plot data
        body_plots[i].set_data([body.position[0]], [body.position[1]])

    return body_plots

# Create the animation
# This might take a moment to generate
animation = FuncAnimation(fig, update_planetary_animation, frames=ANIMATION_FRAMES,
                          interval=20, blit=True)

plt.rcParams['animation.html'] = 'jshtml' # Required for animation to display in Colab
display(animation)

"""### Particle Simulation with Repulsive Forces

This simulation models the movement of three particles in a square space. The particles exhibit elastic collisions with the walls and repel each other with a force inversely proportional to the distance between them, preventing actual collisions.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

class RepulsiveParticle:
    def __init__(self, mass, position, velocity, radius, plot_limit, color='blue'):
        self.mass = mass
        self.position = np.array(position, dtype=float)
        self.velocity = np.array(velocity, dtype=float)
        self.radius = radius
        self.color = color
        self.plot_limit = plot_limit

    def update_state(self, dt, total_force):
        # Update velocity based on total force (F=ma => a=F/m)
        acceleration = total_force / self.mass
        self.velocity += acceleration * dt

        # Update position
        self.position += self.velocity * dt

        # Handle wall collisions
        if not (0 <= self.position[0] <= self.plot_limit):
            self.velocity[0] *= -1  # Reverse x-velocity
            # Reposition to prevent sticking to the wall
            self.position[0] = np.clip(self.position[0], 0, self.plot_limit)

        if not (0 <= self.position[1] <= self.plot_limit):
            self.velocity[1] *= -1  # Reverse y-velocity
            # Reposition to prevent sticking to the wall
            self.position[1] = np.clip(self.position[1], 0, self.plot_limit)

def calculate_repulsive_force(p1, p2, k_repel):
    # Vector from p1 to p2
    r_vec = p2.position - p1.position
    distance = np.linalg.norm(r_vec)

    # Prevent division by zero and very strong forces when particles are extremely close
    # The problem states "this force quickly increases so they never collide",
    # so a small epsilon is appropriate to prevent direct overlap and extreme values.
    if distance < 0.1:  # Define a minimum effective distance to avoid numerical instability
        distance = 0.1

    # Repulsive force magnitude F = k_repel / distance
    force_magnitude = k_repel / distance

    # Force direction (away from each other)
    # The force on p1 is in the opposite direction of r_vec (p2->p1)
    # The force on p2 is in the direction of r_vec (p1->p2)
    force_direction = r_vec / distance

    return -force_magnitude * force_direction, force_magnitude * force_direction


# Simulation parameters
K_REPEL = 50.0  # Repulsion constant (adjust for stronger/weaker repulsion)
SIM_TIME_STEP_PARTICLE = 0.01 # dt for particle simulation
PLOT_LIMIT_PARTICLE = 100 # Extent of the square space

# Initialize particles
particles_repel = [
    RepulsiveParticle(mass=1.0, position=[20, 20], velocity=[10, 15], radius=5, plot_limit=PLOT_LIMIT_PARTICLE, color='red'),
    RepulsiveParticle(mass=1.0, position=[80, 80], velocity=[-12, -8], radius=5, plot_limit=PLOT_LIMIT_PARTICLE, color='green'),
    RepulsiveParticle(mass=1.0, position=[20, 80], velocity=[15, -10], radius=5, plot_limit=PLOT_LIMIT_PARTICLE, color='blue')
]

# Setup the plot for animation
fig_repel, ax_repel = plt.subplots(figsize=(8, 8))
ax_repel.set_xlim(0, PLOT_LIMIT_PARTICLE)
ax_repel.set_ylim(0, PLOT_LIMIT_PARTICLE)
ax_repel.set_aspect('equal', adjustable='box')
ax_repel.set_title('Particle Simulation with Repulsive Forces')

# Create scatter plots for particles
particle_plots = []
for p in particles_repel:
    plot, = ax_repel.plot(p.position[0], p.position[1], 'o', color=p.color, markersize=p.radius * 2)
    particle_plots.append(plot)

def update_repulsive_animation(frame):
    num_particles = len(particles_repel)
    # Initialize total forces for each particle to zero
    total_forces = [np.array([0.0, 0.0]) for _ in range(num_particles)]

    # Calculate pairwise repulsive forces
    for i in range(num_particles):
        for j in range(i + 1, num_particles): # Iterate only over unique pairs
            force_on_i, force_on_j = calculate_repulsive_force(particles_repel[i], particles_repel[j], K_REPEL)
            total_forces[i] += force_on_i
            total_forces[j] += force_on_j

    # Update each particle's state
    for i, p in enumerate(particles_repel):
        p.update_state(SIM_TIME_STEP_PARTICLE, total_forces[i])
        particle_plots[i].set_data([p.position[0]], [p.position[1]])

    return particle_plots


# Create the animation
animation_repel = FuncAnimation(fig_repel, update_repulsive_animation, frames=None,
                                interval=20, blit=True)

plt.rcParams['animation.html'] = 'jshtml' # Required for animation to display in Colab
display(animation_repel)

"""напиши программу имитации движения большого количества частиц со случайными скоростями и направлениями, с визуальной демонстрацией

Certainly! I will create a program to simulate the movement of a large number of particles with random velocities and directions, along with a visual demonstration. This will involve using matplotlib for animation.

The particle simulation with animation has been successfully generated and displayed in the output. You should now see the animated movement of the particles within the defined boundaries.

The particle simulation with visualization has been successfully completed. You should have seen an animation of particles moving randomly and bouncing off walls.

Is there anything else I can help you with regarding this simulation or any other task?

The particle simulation with visualization has been successfully completed. You should have seen an animation of particles moving randomly and bouncing off walls.

Is there anything else I can help you with regarding this simulation or any other task?


напиши программу моделирования движения нескольких планет вокруг звезды по близким орбитам так, чтобы их движение зависело не только от притяжения звезды, но и от взаимных притяжений между планетами

Let's create a simulation for planetary motion around a star, including mutual gravitational attractions between the planets! This will involve defining celestial bodies with mass, position, and velocity, and then calculating the gravitational forces between all of them at each time step to update their movement.

The planetary motion simulation encountered an error during animation. The set_data method for updating the plot requires the x and y coordinates to be provided as sequences, even if it's just a single point. I will fix the update_planetary_animation function in cell eb047380 to correctly pass the position data as sequences.

I've applied the fix to the planetary motion simulation code in cell eb047380. Please execute this cell again to see the animation with the gravitational interactions between the planets.

I have already provided the necessary fix for the planetary motion simulation. Please execute cell eb047380 again to see the animation with the corrected code.

The planetary motion simulation with mutual gravitational attractions has been successfully generated and is now displayed in the output of cell eb047380. You should see the star and planets orbiting, with their paths influenced by each other.

увеличь длительность моделирования - пока не будет нажата кнопка "стоп"

You're asking to make the simulation run indefinitely until a stop button is pressed. While matplotlib.animation in Colab doesn't directly support an interactive 'stop button' within the animation output itself, we can make the animation run continuously. You can then manually stop the cell execution by clicking the square 'stop' button that appears next to the cell during execution.

I will modify cell eb047380 to set ANIMATION_FRAMES to None, which will make the animation run until you manually stop the cell.

Вы остановили генерацию этого ответа.

сделай анимацию того же движения планет, но пусть планет будет больше (10), они будут вращаться по более близким друг к другу орбитам и будут больше влиять друг на друга (напр., немного приближаться), при этом возвращаясь к своим основным орбитам после взаимодействия.

Okay, I will modify the planetary simulation to include 10 planets orbiting closer to each other, with increased mass to make their mutual gravitational influence more visible. You should observe them perturbing each other's orbits and then returning to their general paths. Please run cell eb047380 again to see the updated simulation.

Напиши программу моделирования движения 3 частиц в квадратном пространстве. Частицы абсолютно упруго отталкиваются от стенок квадрата. При сближении частицы начинают отталкиваться друг от друга с силой, обратно пропорциональной расстоянию между ними; эта сила быстро возрастает при сближении частиц, так что они никогда не сталкиваются; после такого сближения они разлетаются в противоположные стороны. Покажи это визуально.
"""

