# -*- coding: utf-8 -*-
"""Test-Graphics-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z0ck3NC77VibOQbJtcGLIVwokmCReMe2

Проводим опыты над гугл-колаб. Здесь - графика.
2026-07-02
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Генерируем случайные данные
x = np.linspace(0, 10, 100)
y = np.sin(x)

# Настройка стилей Seaborn
sns.set_theme(style="darkgrid")

# Построение графика
plt.figure(figsize=(8, 4))
plt.plot(x, y, label="Синусоида", color="purple", linewidth=2)
plt.title("Простой график в Colab: синусоида")
plt.xlabel("Ось X")
plt.ylabel("Ось Y")
plt.legend()
plt.show()

import plotly.express as px
import pandas as pd

# Создаем тестовый датафрейм
df = pd.DataFrame({
    "Фрукт": ["Яблоки", "Бананы", "Апельсины", "Яблоки", "Бананы", "Апельсины"],
    "Количество": [4, 5, 6, 2, 4, 10],
    "Город": ["Москва", "Москва", "Москва", "Сочи", "Сочи", "Сочи"]
})

# Строим интерактивную столбчатую диаграмму
fig = px.bar(df, x="Фрукт", y="Количество", color="Город", barmode="group", title="Продажи по городам")
fig.show()

from sklearn.datasets import load_iris
import pandas as pd

# Загружаем датасет и выводим его
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df

import networkx as nx
import matplotlib.pyplot as plt

G = nx.erdos_renyi_graph(20, 0.2)
plt.figure(figsize=(6, 6))
nx.draw_networkx(G, node_color='lightblue', edge_color='gray')
plt.axis('off')
plt.show()

import folium

# Создаем карту с центром на Красной площади
m = folium.Map(location=[55.753930, 37.620795], zoom_start=15)
folium.Marker([55.753930, 37.620795], popup="Москва").add_to(m)
m

# Убедитесь, что библиотека установлена
!pip install -q mermaid-python

# Правильный импорт класса с большой буквы
from mermaid import Mermaid

diagram_code = """
graph TD
    A[Старт] --> B[Процесс]
    B --> C[Конец]
"""

# Просто создаем объект. Colab сам отобразит его, так как это последняя строка в ячейке.
Mermaid(diagram_code)

import graphviz

# Ваша диаграмма в формате DOT
dot_code = """
digraph G {
    A -> B;
    A -> C;
    B -> D;
    C -> D;
}
"""

# Отображение диаграммы
graphviz.Source(dot_code)

dot_code = """
graph AustriaBorders {
    node [shape=box, style=filled, color=lightgrey, fontname="Arial"];

    // Регионы
    Wien [label="Вена"];
    Niederoesterreich [label="Нижняя Австрия"];
    Burgenland [label="Бургенланд"];
    Steiermark [label="Штирия"];
    Oberoesterreich [label="Верхняя Австрия"];
    Salzburg [label="Зальцбург"];
    Kaernten [label="Каринтия"];
    Tirol [label="Тироль"];
    Vorarlberg [label="Форарльберг"];

    // Связи (границы)
    Wien -- Niederoesterreich;

    Niederoesterreich -- Burgenland;
    Niederoesterreich -- Steiermark;
    Niederoesterreich -- Oberoesterreich;

    Burgenland -- Steiermark;

    Oberoesterreich -- Steiermark;
    Oberoesterreich -- Salzburg;

    Steiermark -- Salzburg;
    Steiermark -- Kaernten;
    Steiermark -- Tirol;

    Salzburg -- Kaernten;
    Salzburg -- Tirol;

    Kaernten -- Tirol;

    Tirol -- Vorarlberg;
}
"""

graphviz.Source(dot_code)

dot_code = """
graph CanadaBorders {
    node [shape=box, style=filled, fontname="Arial"];

    // ==========================================
    // ТЕРРИТОРИИ (Светло-серый цвет)
    // ==========================================
    node [color=lightgrey];
    Yukon [label="Юкон"];
    NWT [label="Северо-Западные территории"];
    Nunavut [label="Нунавут"];

    // ==========================================
    // ПРОВИНЦИИ (Голубой цвет)
    // ==========================================
    node [color=lightblue];
    BC [label="Британская Колумбия"];
    Alberta [label="Альберта"];
    Saskatchewan [label="Саскачеван"];
    Manitoba [label="Манитоба"];
    Ontario [label="Онтарио"];
    Quebec [label="Квебек"];
    NL [label="Ньюфаундленд и Лабрадор"];
    NB [label="Нью-Брансуик"];
    NS [label="Новая Шотландия"];
    PEI [label="Остров Принца Эдуарда"];

    // ==========================================
    // СУХОПУТНЫЕ ГРАНИЦЫ (Сплошные линии)
    // ==========================================
    Yukon -- NWT;
    Yukon -- BC;

    NWT -- Nunavut;
    NWT -- BC;
    NWT -- Alberta;
    NWT -- Saskatchewan;
    NWT -- Manitoba;

    Nunavut -- Saskatchewan; // Точка "Четыре угла"
    Nunavut -- Manitoba;
    Nunavut -- NL;          // Остров Киллиник

    BC -- Alberta;
    Alberta -- Saskatchewan;
    Saskatchewan -- Manitoba;
    Manitoba -- Ontario;
    Ontario -- Quebec;

    Quebec -- NL;
    Quebec -- NB;
    NB -- NS;

    // ==========================================
    // ИСКУССТВЕННЫЕ И МОРСКИЕ СВЯЗИ
    // ==========================================
    // Мост Конфедерации
    NB -- PEI [style=dashed, color=darkgreen, label="мост"];

    // Морские границы (Залив Святого Лаврентия и др.)
    edge [style=dashed, color=blue, label="вода"];
    Quebec -- PEI;
    Quebec -- NS;
    NL -- NS;          // Пролив Кабота
    PEI -- NS;         // Пролив Нортамберленд
    Nunavut -- Quebec; // Гудзонов пролив
}
"""

graphviz.Source(dot_code)

from random import randint

nums = [ randint(1, 10) for _ in range(10)]
print(nums)

diag = """
graph Nums {
"""

for i in range(len(nums)-1):
    diag += f"{nums[i]} -- {nums[i+1]};\n"

diag += """}
"""
print(diag)

graphviz.Source(diag)