# -*- coding: utf-8 -*-
"""Test-AI-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tHlzNQwNGLuwW1OCUYYm0NWEQJu5tI5
"""

import matplotlib.pyplot as plt
import numpy as np

image = np.array([[0, 1, 1], [0, 1, 1], [0, 0, 0]])

plt.imshow(image, cmap="gray", interpolation="nearest")
plt.axis("off")
plt.show()

vectorized = image.flatten()
print(vectorized)

# 0. Подключение библиотек

from keras.datasets import mnist
from keras.layers import Dense, Flatten, Input
from keras.models import Sequential
import matplotlib.pyplot as plt

# 1. Загрузка и подготовка данных

(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0

# 2. Построение модели нейросети

model = Sequential(
    [
        Input(shape=(28, 28)),
        Flatten(),
        Dense(128, activation="relu"),
        Dense(10, activation="softmax"),
    ]
)

# 3. Компиляция модели

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

# 4. Обучение модели

print("Начинаем обучение нейросети...")
history = model.fit(
    X_train, y_train, epochs=5, validation_data=(X_test, y_test)
)

# 5. Оценка точности модели

test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Точность модели на тестовых данных: {test_accuracy:.2f}")

from keras.datasets import mnist
import matplotlib.pyplot as plt

# Загрузка набора данных MNIST

data = mnist.load_data()

(X_train, y_train), (X_test, y_test) = data

# Просмотр первого изображения

plt.imshow(X_train[0], cmap='gray')
plt.title(f"Цифра: {y_train[0]}")
plt.show()

print("Числовое представление изображения:")
print(X_train[0])  # Вывод матрицы пикселей

# 0. Подключение библиотек

from keras.models import Sequential
from keras.layers import Dense, Flatten, Input
from keras.datasets import mnist
import matplotlib.pyplot as plt

# 1. Загрузка и подготовка данных

(X_train, y_train), (X_test, y_test) = mnist.load_data()

# 2. Нормализация данных (диапазон [0, 1])

X_train, X_test = X_train / 255.0, X_test / 255.0

model = Sequential(
    [
        Input(shape=(28, 28)),
        Flatten(),
        Dense(128, activation="relu"),
        Dense(10, activation="softmax"),
    ]
)

# 3. Компиляция модели

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 4. Обучение модели

history = model.fit(
    X_train, y_train, epochs=5, validation_data=(X_test, y_test)
)

# 5. Оценка точности модели

test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Точность модели на тестовых данных: {test_accuracy:.2f}")

# 6. Демонстрация предсказания

import numpy as np
index = np.random.randint(15, len(X_test))

# Случайное изображение из тестового набора

prediction = model.predict(X_test[index:index+1])
predicted_label = np.argmax(prediction)

plt.imshow(X_test[index], cmap='gray')
plt.title(f"Предсказанная цифра: {predicted_label}")
plt.show()