# tem-dist.tpl 2020-05-27

python python
питон python
джанго python/django
django python/django
php php
javascript js
джаваскрипт js
java java
джава java
джаве java
fossil web/fossil
lisp lisp
лисп lisp
ajax web/ajax
rest,api web/rest
jquery js/jquery
awk awk
common,lisp lisp/common
pycharm python/tools
kotlin kotlin
algorithm the/algo
алгоритм the/algo
кнут the/knuth
tex,font dtp/tex/fonts
tcpip web/tcpip
udp web/udp
web,design web/design
web,font web/fonts
font fonts
dtp dtp
tex,dtp dtp/tex
flask python/flask
tensorflow python/tensorflow
asyncio python/async
python,ai python/AI
python,artificial,intelligence python/ai
python,machine,learning python/AI
agile tech/agile
react,native js/react_native
angular js/angular
c++ ccpp/cpp
golang go
julia julia
prolog prolog
pascal pascal
ansible devops/ansible
docker devops/docker
DBMS dbms
mysql dbms/mysql
mariadb dbms/mysql
innodb dbms/mysql
postgres dbms/postgresql
pgsql dbms/postgresql
bottle python/bottle
sqlite dbms/sqlite
sql dbms/sql
нейронны ai/neural_nets
баз,данных dbms
bigdata bigdata
react js/react
forth forth
html web/html
css web/css
asm asm
assembly asm
1c buch/1c
1s buch/1c
vzlom hack/hack
virus hack/hack
вирус hack/hack
вторжен hack/hack
взлом hack/hack
взлам hack/hack
наруш hack/hack
защита hack/hack
защищ hack/hack
vred hack/hack
взлом hack/hack
безопас hack/secure
secur hack/secure
вред hack/hack
хакер hack
hacker hack
algol68 algol
алгол68 algol68
algol algol
алгол algol
паскал pascal
logo logo
algo the/algo
android os/android
linux os/linux
линукс os/linux
unix os/unix
financ office/buch
word office/ms/word
excel office/ms/excel
powerpoint office/ms/powerpoint
ms,office office/ms
microsoft,office ms/office
apple company/apple
ibm company/ibm
microsoft company/microsoft
google company/google
yandex company/yandex
яндекс company/yandex
intel company/intel
libre,office office/foss
open,office office/foss
arduino os/arduino
acrhit,pattern the/arch
bayes the/bayes
rest,api web/rest
graphql web/graphql
deep,learn ai/deep
xml xml
mean,stack web/mean
game prog/game
интеллект ai/ai
школьни edu
обучени edu
школа edu
school edu
math the/math
гугл company/google
technolog the/tech
технологи the/tech
hardware hard
аппарат hard
программ soft
software soft
