# tem-dist.tpl 2021-05-16
freebsd os/freebsd
perl perl
ainl ai/ainl
ысшая,матем the/math
ысшей,мат the/math
python,ai python/ai
python,artificial,intelligence python/ai
python,machine,learning python/ai
pandas python/sci
python python
питон python
джанго python/django
django python/django
php php
javascript js
джаваскрипт js
java java
джава java
джаве java
fossil web/fossil
lisp lisp
лисп lisp
ajax web/ajax
rest,api web/rest
jquery js/jquery
awk awk
common,lisp lisp/common
pycharm python/tools
kotlin kotlin
algorithm the/algo
алгоритм the/algo
кнут the/knuth
tex,font dtp/tex/fonts
tcpip web/tcpip
udp web/udp
web,design web/design
web,font web/fonts
font fonts
dtp dtp
tex,dtp dtp/tex
flask python/flask
tensorflow python/ai/tensorflow
asyncio python/async
agile tech/agile
react,native js/react_native
angular js/angular
c++ ccpp
golang go
julia julia
prolog prolog
pascal pascal
ansible devops/ansible
docker devops/docker
DBMS dbms
mysql dbms/mysql
mariadb dbms/mysql
innodb dbms/mysql
postgres dbms/postgresql
pgsql dbms/postgresql
bottle python/bottle
sqlite dbms/sqlite
sql dbms/sql
нейронны ai/neural_nets
баз,данных dbms
bigdata bigdata
react js/react
forth forth
html web/html
css web/css
asm asm
assembly asm
1c buch/1c
1s buch/1c
vzlom hack/hack
virus hack/hack
вирус hack/hack
вторжен hack/hack
взлом hack/hack
взлам hack/hack
наруш hack/hack
защита hack/hack
защищ hack/hack
vred hack/hack
взлом hack/hack
безопас hack/secure
secur hack/secure
вред hack/hack
хакер hack
hacker hack
algol68 algol
алгол68 algol68
algol algol
алгол algol
паскал pascal
logo logo
algo the/algo
android os/android
linux os/linux
линукс os/linux
unix os/unix
financ office/buch
word office/ms/word
excel office/ms/excel
powerpoint office/ms/powerpoint
ms,office office/ms
microsoft,office ms/office
apple company/apple
ibm company/ibm
microsoft company/microsoft
google company/google
yandex company/yandex
яндекс company/yandex
intel company/intel
libre,office office/foss
open,office office/foss
arduino os/arduino
acrhit,pattern the/arch
bayes the/bayes
rest,api web/rest
graphql web/graphql
deep,learn ai/deep
xml xml
mean,stack web/mean
game prog/game
интеллект ai/ai
школьни edu
обучени edu
школа edu
school edu
math the/math
гугл company/google
technolog the/tech
технологи the/tech
hardware hard
аппарат hard
программ soft
software soft
node js/node
c_prog ccpp
d3 js
fortran fortran
r_prog r
hacking hack
haskell haskell
go go
сети nets
nets nets
network nets
bash os/linux
_c_ ccpp
aws nets/aws
bazy dbms
dannyh dbms
cisco nets/cisco
git tech/git
visual,studio tools/edit
geany tools/edit
atom tools/edit
powershell os/windows/tools
windows,server os/windows/server
windows,7 os/windows/7
windows,10 os/windows/10
windows os/windows
cloud,native web/cloud-native
test,auto tech/test/auto
test tech/test
тест tech/test
csharp ccpp
c# ccpp
nlp ai/nlp
natural,language,proces ai/nlp
nginx web/nginx
devops devops
typescript js/typescript
algebra math/algebra
geometry math/geometry
apache web/apache
serverless web/serverless
ubuntu os/linux/ubuntu
web web
statist math/stat
математ math
адинист tools/admin
уравнени math
scrum tech/scrum
kanban tech/scrum
естест,язык /ai/nlp
комбинатор math
kubernetes tech/kubernetes
openssl nets/ssl
swift pl/swift
helm tech/helm
mikrotik nets/mikrotik
machine,learn ai/ml
jenkins tech/jenkins
cloud nets/cloud
spa web/spa
vim tools/edit/vim
rust rust
data,science ai/data-science
реальност ai/reality
computer,science the/cs
science the/science
наук the/science
научн the/science
blockchain tech/blockchain
blokchein tech/blockchain
raspbe hard/raspberrypi
cassan dbms/cassandra
oracle nets/oracle
tcp,ip nets/tcpip
database dbms
ip,addr net/tcpip
ai ai
субд dbms
сети nets
админ tools/admin
admin tools/admin
график math
функц,прог prog/func
функци math
asterisk tools/asterisk
bootstrap web/bootstrap
api web/api
operation,system os
